[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
conditional-plugin = "M5SbjhbprZ4xomfjxr9EYxpsRbRc1jkFS4Yb5r2wZKg"
saipher = "HzgcvSu1HMonZMuMdTiTwDyAKs5874k9dy9NqknmHy2z"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.test.ts"

[[test.genesis]]
address = "GovER5Lthms3bLBqWub97yVrMmEogzX7xNjdXpPPCVZw"
program = "tests/spl_governance_3_1_1.so"

